name: "JFrog-GitHub OIDC Integration"
on: push
#test
# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: 'davidfa-github'
           oidc-audience: 'support'
           version: latest
       - name: Get id token
         run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
      
       - name: Ping Artifactory
         run: jf rt ping
       - name: Print
         run: env | sort
       - name: Token
         run: echo $JF_ACCESS_TOKEN
       - name: Download file
         run: jf rt dl example-repo-local/file.txt .
       - name: Show file content
         run: cat file.txt
