name: oidc-poc

on:
  push:
    branches:
      - '*'

jobs:
  auth:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get ID token
        run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=support" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV

      - name: Exchange token for access token
        env:
          ID_TOKEN: ${{ env.ID_TOKEN }}
          JFROG_PLATFORM_URL: https://elinaf.jfrog.io
        run: |
          ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" "${JFROG_PLATFORM_URL}/access/api/v1/oidc/token" \
          -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"davidfa-github\", \"project_key\": \"pr2\"}" | jq .access_token | tr -d '"')
          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create test file
        run: |
           echo "ceci est un test" > oidc-poc

      - name: Deploy to Artifactory
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
          JFROG_PLATFORM_URL: https://elinaf.jfrog.io
        run: |
          curl -H "Authorization: Bearer $ACCESS_TOKEN" -T oidc-poc "${JFROG_PLATFORM_URL}/artifactory/ronma-generic-local/oidc-poc"

      - name: Generate build-info JSON
        run: |
          BUILD_NAME="oidc-poc-build"
          BUILD_NUMBER=$(date +%Y%m%d%H%M%S)
          ARTIFACT_NAME="oidc-poc"
          SHA1=$(sha1sum "$ARTIFACT_NAME" | awk '{ print $1 }')
          MD5=$(md5sum "$ARTIFACT_NAME" | awk '{ print $1 }')
          STARTED=$(date -u +"%Y-%m-%dT%H:%M:%S.000+0000")

          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "STARTED=$STARTED" >> $GITHUB_ENV

          cat > buildinfo.json <<EOF
          {
           "version" : "1.0.1",
           "name": "${BUILD_NAME}",
           "number": "${BUILD_NUMBER}",
           "started": "${STARTED}",
           "agent": {
           "name": "GitHub Actions",
           "version": "1.0"
           },
           "modules": [
           {
           "id": "oidc-module",
           "artifacts": [
            {
            "type": "file",
            "sha1": "${SHA1}",
            "md5": "${MD5}",
            "name": "${ARTIFACT_NAME}"
          }
          ]
          }
          ]
          }
          EOF


          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Publish build-info to Artifactory
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
          JFROG_PLATFORM_URL: https://elinaf.jfrog.io
        run: |
          curl -X PUT \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -d @buildinfo.json \
            "$JFROG_PLATFORM_URL/artifactory/api/build"

