name: "JFrog-GitHub OIDC Integration"
on: push
#test
#test7
# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: 'davidfa-github'
           oidc-audience: 'support'
           version: latest
       - name: Ping Artifactory
         run: jf rt ping
      # - name: Print
        # run: env | sort
       - name: Download file
         #run: jf rt dl example-repo-local/b.txt .
         run: jf rt dl ronma-generic-local/shani-values.yaml .
       - name: Show file content
         run: cat shani-values.yaml
